services:
  api:
    command: uvicorn main:app --reload
    volumes:
      - ./api:/app
    ports:
      - 8000:8000

  web:
    build:
      dockerfile: ./Dockerfile-dev
    command: npm run dev
    volumes:
      - ./web:/app
      - /app/node_modules

networks:
  external_network:
  internal_network:
    internal: true
