services:
  db:
    restart: always
    image: postgres:14-alpine
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    networks:
      - internal_network
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  api:
    restart: always
    build: ./api
    networks:
      - internal_network
    depends_on:
      - db

  web:
    restart: always
    build: ./web
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - api
      - db

networks:
  external_network:
  internal_network:
    internal: true
