services:
  db:
    env_file:
      - path: .env.development
        required: true
      - path: .env.production
        required: false

  api:
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file:
      - path: .env.development
        required: true
      - path: .env.production
        required: false
    networks:
      - external_network
      - internal_network
    volumes:
      - ./api:/app
    ports:
      - 127.0.0.1:8000:8000

  web:
    build:
      dockerfile: ./Dockerfile-dev
    command: npm run dev
    volumes:
      - ./web:/app
      - /app/node_modules

networks:
  external_network:
  internal_network:
    internal: true
